services:
  healthcore-api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: healthcore-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - healthcore_data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  healthcore-frontend:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
      shm_size: 1gb
    container_name: healthcore-frontend
    restart: unless-stopped
    ports:
      - "5005:80"
    depends_on:
      healthcore-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 128M
    environment:
      - NODE_ENV=production

volumes:
  healthcore_data:
    driver: local
