services:
  mobilemed-api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: mobilemed-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - mobilemed_data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  mobilemed-frontend:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: mobilemed-frontend
    restart: unless-stopped
    ports:
      - "5005:80"
    depends_on:
      mobilemed-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M

volumes:
  mobilemed_data:
    driver: local
