name: Deploy to OCI VM

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite execução manual

jobs:
  deploy:
    name: Deploy MobileMed to OCI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}

      - name: Add OCI VM to known hosts
        run: ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts

      - name: Create project directory on OCI
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.OCI_HOST }} "
            sudo mkdir -p /var/www/DesafioTecnico
            sudo chown ubuntu:ubuntu /var/www/DesafioTecnico
          "

      - name: Sync project files to OCI
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='bin' \
            --exclude='obj' \
            --exclude='.env.local*' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ubuntu@${{ secrets.OCI_HOST }}:/var/www/DesafioTecnico/

      - name: Deploy and build on OCI
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.OCI_HOST }} "
            cd /var/www/DesafioTecnico
            
            echo '🚀 Iniciando deploy do MobileMed...'
            
            # Parar containers existentes
            docker-compose down || true
            
            # Build e start dos containers
            echo '🔨 Fazendo build dos containers...'
            docker-compose up --build -d
            
            # Aguardar containers iniciarem
            echo '⏳ Aguardando containers iniciarem...'
            sleep 10
            
            # Verificar status dos containers
            echo '📊 Status dos containers:'
            docker-compose ps
            
            # Limpeza de imagens não utilizadas
            echo '🧹 Limpando imagens não utilizadas...'
            docker image prune -f
            
            # Forçar atualização do cache do navegador
            echo '🔄 Forçando atualização do cache do navegador...'
            chmod +x scripts/clear-browser-cache.sh
            ./scripts/clear-browser-cache.sh
            
            echo '✅ Deploy concluído com sucesso!'
            echo '🌐 HealthCore disponível em:'
            echo '   - API: http://129.153.86.168:5000/health'
            echo '   - Frontend: http://129.153.86.168:5005'
            echo '💡 Se o cache ainda persistir, instrua os usuários a:'
            echo '   - Pressionar Ctrl+F5 (Windows/Linux) ou Cmd+Shift+R (Mac)'
            echo '   - Ou abrir em aba anônima/privada'
            echo '   - Ou limpar cache do navegador manualmente'
          "
